In [1]:
1+1

2

In [2]:
println("This is so cool!!!")

This is so cool!!!


# Part 1: Julia Basics

### for loop

In [3]:
l = ["This", "is", "so", "cool"] 
for i in l
    println(i) 
end

This
is
so
cool


In [4]:
for i in 1:5
    println(i)
end

1
2
3
4
5


### while loop

In [5]:
m = 1
while m<= 5
    println(m)
    m = m + 1
end

1
2
3
4
5


### if-else statement

In [21]:
A = 100
B = 50
if A > B
    println("A is greater than B")
elseif A < B
    println("A is less than B")
else
    println("A is equal to B")
end

A is greater than B


### create function

In [7]:
newfunction1(a, b, c) = a + b + c
newfunction1(1, 1, 1)

3

In [8]:
function newfunction2(x,y)
           x + y
end
newfunction2(1, 1)

2

In [9]:
#if you want to get more from the function: may use return
function newfunction3(x,y)
    return([x + y, x-y])
end
newfunction3(1, 1)

2-element Vector{Int64}:
 2
 0

### install package

In [ ]:
using Pkg

Pkg.add("LinearAlgebra")  # we need the norm funciton
using LinearAlgebra

Pkg.add("Statistics") # we need the mean function
using Statistics

# Part 2: Julia Tutorial

### Chapter 1.1 vector

### Create vector

In [10]:
# can separate using ","
x = [ -1.1, 0.0, 3.6, -7.2 ]
length(x)

4

In [11]:
# can also separate using ";"
y = [ -1.1; 0.0; 3.6; -7.2 ]
length(y)

4

In [24]:
# Wrong ways to create vector
a = [ 1 2 ]
b = ( 1, 2 )
println(a, typeof(a))
println(b, typeof(b))

[1 2]Matrix{Int64}
(1, 2)Tuple{Int64, Int64}


### Indexing

In [13]:
x = [ -1.1, 0.0, 3.6, -7.2 ]
x[3]

3.6

In [14]:
x[3] = 4.0
x

4-element Vector{Float64}:
 -1.1
  0.0
  4.0
 -7.2

### Assignment

In [28]:
x = [ -1.1, 0.0, 3.6, -7.2 ]
y = x
x[3] = 4.0
println("y = ", y) # y will change upon the change of x
y[1] = 2.0
println("x = ", x)  # x will also be changed when y is changed
println("y = ", y)
x == y

y = [-1.1, 0.0, 4.0, -7.2]
x = [2.0, 0.0, 4.0, -7.2]
y = [2.0, 0.0, 4.0, -7.2]


true

### Copy

In [27]:
x = [ -1.1, 0.0, 3.6, -7.2 ]
y = copy(x)  # only copy the values, then x and y will function separately
x[3] = 4.0
println("y = ", y)
y[1] = 2.0
println("x = ", x)

y = [-1.1, 0.0, 3.6, -7.2]
x = [-1.1, 0.0, 4.0, -7.2]


### Vector equality

In [32]:
x = [ -1.1, 0.0, 3.6, -7.2 ]
y = copy(x)
y[3] = 4.0
println("y == x: ", y == x)

z = x
z[3] = 4.0
println("z == x: ", z == x)

y == x: false
z == x: true


true

### Scalars versus 1-vectors

In [38]:
x = [ 1.3 ]
y = 1.3
println(typeof(x))
println(typeof(y))
println("x == y: ", x == y)
println("x[1] == y: ", x[1] == y)

Vector{Float64}
Float64
x == y: false
x[1] == y: true


###  Stacked vectors

In [39]:
x=[1, -2]; y=[1, 1, 0];
z1 = [ x; y ]   # Concatenate using semicolon
z2 = vcat(x, y) # Concatenate using vcat
println("z1 == z2: ", z1 == z2)

z1 == z2: true


### Subvectors and slicing

In [41]:
x = [ 9, 4, 3, 0, 5 ]
y = x[2:4]
println("y = " , y)
x[4:5] = [ -2, -3 ]
println("x = " , x)

y = [4, 3, 0]
x = [9, 4, 3, -2, -3]


### Lists of vectors

In [48]:
x = [1.0, 0 ];   y = [ 1.0, -1.0 ];   z = [ 0, 1.0];
list1 = [ x, y, z ]
list2 = ( x, y, z )
list1 == list2
println(list1, " ",  typeof(list1))
println(list2, " ",  typeof(list2))

[[1.0, 0.0], [1.0, -1.0], [0.0, 1.0]] Vector{Vector{Float64}}
([1.0, 0.0], [1.0, -1.0], [0.0, 1.0]) Tuple{Vector{Float64}, Vector{Float64}, Vector{Float64}}


### Zero and one vectors

In [49]:
zeros(3) # create vector of 3 dimension, all of them are 0
ones(2)  # create vector of 2 dimension, all of them are 1
println(zeros(3))
println(ones(2))

[0.0, 0.0, 0.0]
[1.0, 1.0]


### Random vectors

In [21]:
rand(2)     # drawn from 0-1 randomly
randn(2)    # drawn from standard normal distribution
println(rand(2))
println(randn(2))

[0.7612257752451703, 0.4792644789787168]
[-1.0075276959321537, -0.6432419892560122]


### Chapter 1.2 Vector addition

In [23]:
a = [0,7,3] +[1,2,0]     # Vector addition
b = [ 1, 9 ] - [ 1, 1]  # Vector subtraction
println(a)
println(b)

[1, 9, 3]
[0, 8]


### Chapter 1.3 Scalar-vector multiplication

### Scalar-vector multiplication and division

In [53]:
x = [ 0, 2, -1 ]
println(2 * x )    # Scalar-vector multiplication
println(x * 2)
println(x / 0.1)
println(3 / x)

[0, 4, -2]
[0, 4, -2]
[0.0, 20.0, -10.0]
[0.0 1.2000000000000002 -0.6000000000000001]


In [54]:
println(x + 2)

LoadError: MethodError: no method matching +(::Vector{Int64}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::T, ::Integer) where T<:AbstractChar at char.jl:223
  ...

### Scalar-vector addition

In [24]:
[ 1.1, -3.7, 0.3 ] .- 1.4
[ 1.1, -3.7, 0.3 ] .+ 1.4

3-element Vector{Float64}:
  2.5
 -2.3000000000000003
  1.7

### Elementwise operations with a scalar

In [55]:
w = [1,2,2]; z = [1,2,3]
println(w == z)  # check the entire variable
println(w .== z) # check each component

false
Bool[1, 1, 0]


### Chapter 1.4 Innder product

In [26]:
x = [ -1, 2, 2 ];
y = [ 1, 0, -3 ];
x'*y

-7

### Chapter 1.5 Complexity of vector computations

In [27]:
a = randn(10^5); b = randn(10^5)
@time a'*b
@time a'*b

  0.080585 seconds (58.04 k allocations: 3.744 MiB, 81.68% compilation time)
  0.000084 seconds (2 allocations: 32 bytes)


-65.30542253333772

### Chaper 2.1 Linear functions

In [28]:
f(x) = x[1] + x[2] - x[4]^2
f([-1,0,1,2])

-5

In [56]:
a = [-2, 0, 1, -3]
f(x) = a'*x
x=[2,2,-1,1]; y=[0,1,-1,0];
alpha = 1.5; beta = -3.7;
lhs = f(alpha * x + beta * y) # scalar-vector multiplication
rhs = alpha * f(x) + beta * f(y)
lhs == rhs # which is the definition of linear

true

### Chapter 3.1 Norm

In [31]:
using Pkg
Pkg.add("LinearAlgebra")  # we need the norm funciton
using LinearAlgebra
x = [ 2, -1, 2 ];
norm(x)    # norm: will calculate the two norm
sqrt(x'*x) # inner product with itself
sqrt(sum(x.^2))  # component-wise x squared

3.0

### Chapter 3.2 Distance

In [33]:
u = [1.8, 2.0, -3.7, 4.7]
v = [0.6, 2.1, 1.9, -1.4]
w = [2.0, 1.9, -4.0, 4.6]
norm(u-v), norm(u-w), norm(v-w)

(8.36779540858881, 0.3872983346207417, 8.532877591996735)

### Chapter 4.1 Clustering

In [37]:
Pkg.add("Statistics") # we need the mean function
using Statistics

In [40]:
Jclust(x,reps,assignment) =
       mean( [norm(x[i]-reps[assignment[i]])^2 for i=1:length(x)] )
x = [ [0,1], [1,0], [-1,1] ]
reps = [ [1,1], [0,0] ]
assignment = [1,2,1]    
Jclust(x,reps,assignment) 

2.0

### Chapter 5.1 Gram Schmidt Algorithm

In [41]:
function gram_schmidt(a; tol = 1e-10)
q=[]
for i = 1:length(a)
    qtilde = a[i]
    for j = 1:i-1
        qtilde -= (q[j]'*a[i]) * q[j]
    end
    if norm(qtilde) < tol
       println("Vectors are lin0early dependent.")
       return q
end
    push!(q, qtilde/ norm(qtilde))
end;
return q end

gram_schmidt (generic function with 1 method)

In [42]:
a = [ [-1, 1, -1, 1], [-1, 3, -1, 3], [1, 3, 5, 7] ]
q = gram_schmidt(a)

3-element Vector{Any}:
 [-0.5, 0.5, -0.5, 0.5]
 [0.5, 0.5, 0.5, 0.5]
 [-0.5, -0.5, 0.5, 0.5]

In [44]:
b = [ a[1], a[2], 1.3*a[1] + 0.5*a[2] ]
q = gram_schmidt(b)

Vectors are linearly dependent.


2-element Vector{Any}:
 [-0.5, 0.5, -0.5, 0.5]
 [0.5, 0.5, 0.5, 0.5]